# Generated by Django 4.2 on 2025-04-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Elevage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_joueur", models.CharField(max_length=100)),
                ("nombre_males", models.PositiveIntegerField(default=0)),
                ("nombre_femelles", models.PositiveIntegerField(default=0)),
                ("quantite_nourriture", models.PositiveIntegerField(default=0)),
                ("nombre_cages", models.PositiveIntegerField(default=0)),
                ("argent", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
