# Generated by Django 4.2 on 2025-04-09 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lapin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Individu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sexe",
                    models.CharField(
                        choices=[("M", "Mâle"), ("F", "Femelle")], max_length=1
                    ),
                ),
                ("age", models.IntegerField()),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("present", "Présent"),
                            ("vendu", "Vendu"),
                            ("mort", "Mort"),
                            ("gravide", "Gravide"),
                        ],
                        default="present",
                        max_length=10,
                    ),
                ),
                (
                    "elevage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="individus",
                        to="lapin.elevage",
                    ),
                ),
            ],
        ),
    ]
