# Generated by Django 4.2 on 2025-04-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lapin", "0002_individu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="individu",
            name="age",
            field=models.PositiveIntegerField(help_text="Âge en mois"),
        ),
        migrations.AlterField(
            model_name="individu",
            name="etat",
            field=models.CharField(
                choices=[
                    ("P", "Présent"),
                    ("V", "Vendu"),
                    ("M", "Mort"),
                    ("G", "Gravide"),
                ],
                max_length=1,
            ),
        ),
    ]
