# Generated by Django 4.2 on 2025-04-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lapin", "0003_alter_individu_age_alter_individu_etat"),
    ]

    operations = [
        migrations.CreateModel(
            name="Regle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prix_nourriture",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Prix au g de nourriture",
                        max_digits=5,
                    ),
                ),
                ("prix_cage", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "prix_vente_lapin",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "conso_2_mois",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Conso en g/mois pour un lapin de 2 mois",
                        max_digits=4,
                    ),
                ),
                (
                    "conso_3_mois_et_plus",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Conso en g/mois à partir de 3 mois",
                        max_digits=4,
                    ),
                ),
                (
                    "age_min_gravide",
                    models.IntegerField(
                        help_text="Âge minimum (mois) pour être gravide"
                    ),
                ),
                (
                    "age_max_gravide",
                    models.IntegerField(
                        help_text="Âge maximum (mois) pour être gravide"
                    ),
                ),
                ("duree_gestation", models.IntegerField(help_text="Durée en mois")),
                (
                    "nb_max_par_portee",
                    models.IntegerField(help_text="Nombre max de lapereaux par portée"),
                ),
                (
                    "nb_max_individus_par_cage",
                    models.IntegerField(help_text="Nombre normal d'individus par cage"),
                ),
                (
                    "seuil_surpopulation",
                    models.IntegerField(
                        help_text="Seuil à partir duquel il y a surpopulation"
                    ),
                ),
            ],
        ),
    ]
