# Generated by Django 4.2 on 2025-04-12 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lapin", "0005_alter_regle_conso_2_mois_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="elevage",
            name="tour",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
