# Generated by Django 4.2 on 2025-04-12 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lapin", "0006_elevage_tour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elevage",
            name="tour",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
