# Generated by Django 4.2 on 2025-05-05 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lapin', '0008_elevage_fin_du_jeu'),
    ]

    operations = [
    ]
