# Generated by Django 4.2.20 on 2025-04-28 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lapin', '0008_elevage_fin_du_jeu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('malade', models.BooleanField(default=False)),
                ('niveau_sante', models.IntegerField(default=100)),
                ('individu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sante', to='lapin.individu')),
            ],
        ),
    ]
