# Generated by Django 4.2 on 2025-05-04 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lapin", "0009_client"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="avatar",
        ),
    ]
