# Generated by Django 4.2.20 on 2025-04-28 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lapin', '0009_sante'),
    ]

    operations = [
        migrations.AddField(
            model_name='individu',
            name='sante',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individu_sante', to='lapin.sante'),
        ),
        migrations.AlterField(
            model_name='sante',
            name='individu',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='individu_sante', to='lapin.individu'),
        ),
    ]
