# Generated by Django 4.2 on 2025-05-05 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lapin', '0010_tour'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tour',
        ),
    ]
