# Generated by Django 4.2 on 2025-05-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lapin", "0011_elevage_utilisateur"),
    ]

    operations = [
        migrations.AddField(
            model_name="elevage",
            name="a_ajoute_ressources",
            field=models.BooleanField(default=False),
        ),
    ]
