# Generated by Django 4.2 on 2025-05-05 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lapin', '0011_delete_tour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='Numéro du tour', unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('nb_femelles_adultes', models.PositiveIntegerField(default=0)),
                ('nb_males_adultes', models.PositiveIntegerField(default=0)),
                ('nb_lapereaux', models.PositiveIntegerField(default=0)),
                ('elevage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='lapin.elevage')),
            ],
        ),
    ]
