# Generated by Django 4.2.20 on 2025-04-30 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lapin', '0011_elevage_difficulte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sante',
            name='individu',
        ),
        migrations.AlterField(
            model_name='individu',
            name='sante',
            field=models.OneToOneField(default=100, on_delete=django.db.models.deletion.CASCADE, related_name='individu', to='lapin.sante'),
            preserve_default=False,
        ),
    ]
