# Generated by Django 4.2 on 2025-05-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapin', '0012_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='numero',
            field=models.PositiveIntegerField(help_text='Numéro du tour'),
        ),
        migrations.AlterUniqueTogether(
            name='tour',
            unique_together={('numero', 'elevage')},
        ),
    ]
