# Generated by Django 4.2.20 on 2025-04-30 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lapin', '0012_remove_sante_individu_alter_individu_sante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individu',
            name='sante',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individu', to='lapin.sante'),
        ),
    ]
