# Generated by Django 4.2 on 2025-05-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lapin", "0012_elevage_a_ajoute_ressources"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="elevage",
            name="a_ajoute_ressources",
        ),
        migrations.AddField(
            model_name="elevage",
            name="a_ajoute_ressources_tour",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
