# Generated by Django 4.2.20 on 2025-04-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapin', '0014_remove_sante_malade_sante_individu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sante',
            name='malade',
            field=models.BooleanField(default=False),
        ),
    ]
