# Generated by Django 4.2.20 on 2025-04-30 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lapin', '0016_alter_individu_sante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sante',
            name='individu',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sante_individu', to='lapin.individu'),
        ),
    ]
