# Generated by Django 4.2.20 on 2025-04-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapin', '0018_alter_individu_sante'),
    ]

    operations = [
        migrations.AddField(
            model_name='sante',
            name='vivant',
            field=models.BooleanField(default=True),
        ),
    ]
