# Generated by Django 4.2.20 on 2025-05-03 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lapin', '0019_sante_vivant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individu',
            name='sante',
        ),
        migrations.AlterField(
            model_name='sante',
            name='individu',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sante', to='lapin.individu'),
        ),
    ]
