# Generated by Django 4.2 on 2025-05-05 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lapin', '0011_elevage_utilisateur'),
        ('lapin', '0020_remove_individu_sante_alter_sante_individu'),
    ]

    operations = [
    ]
