# Generated by Django 4.2 on 2025-05-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapin', '0021_merge_20250505_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='sante',
            name='vacciné',
            field=models.BooleanField(default=False),
        ),
    ]
