# Generated by Django 4.2 on 2025-05-05 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lapin', '0013_alter_tour_numero_alter_tour_unique_together'),
        ('lapin', '0022_sante_vacciné'),
    ]

    operations = [
    ]
