# Generated by Django 4.2 on 2025-05-06 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lapin", "0013_remove_elevage_a_ajoute_ressources_and_more"),
        ("lapin", "0023_merge_20250505_1736"),
    ]

    operations = []
