# Generated by Django 4.2 on 2025-05-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapin', '0023_merge_20250505_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='nb_mortalites',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tour',
            name='nb_naissances',
            field=models.IntegerField(default=0),
        ),
    ]
