# Generated by Django 4.2 on 2025-05-07 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lapin", "0024_merge_20250506_1113"),
        ("lapin", "0024_tour_nb_mortalites_tour_nb_naissances"),
    ]

    operations = []
